project_name: Network Anomaly Detection
random_seed: 42
feature_engineering:
  selected_features:
  - ' Destination Port'
  - ' Flow IAT Min'
  - ' Init_Win_bytes_backward'
  - Init_Win_bytes_forward
  - ' Fwd IAT Min'
  - ' Flow Duration'
  - Total Length of Fwd Packets
  - ' Bwd Packets/s'
  - ' Total Fwd Packets'
  - Bwd Packet Length Max
  - Flow Bytes/s
  - ' Fwd Packet Length Max'
  - ' Fwd IAT Mean'
  - ' min_seg_size_forward'
  - ' Bwd IAT Min'
  - ' Flow IAT Std'
  - ' Flow IAT Mean'
  - ' Fwd Packet Length Mean'
  - ' Flow Packets/s'
  - ' URG Flag Count'
data_paths:
  - 'final_df\train_df_preprocessed.parquet'
  - 'final_df\test_df_preprocessed.parquet'
